### ISSUE TITLE
Building from source having x4 speedup vs. naive install

### ISSUE THREAD

**Issue by seongminp** [veritas9872/PyTorch-Universal-Docker-Template#22]
Hi. Thank you for releasing this library.

I had a question about this tidbit in the README:

> PyTorch built from source can be x4 faster than a naïve PyTorch install. 

Is there any past discussion or justification about this speedup? Is source install faster both on CPU and GPU? Could it be attributed to better optimization of BLAS or MKL? 

Would love to know more about this.

**Comment by veritas9872** [comment]
The x4 speedup was what I observed on an RTX 3090 before and after using the template. Admittedly, it may not have been the fairest comparison considering the CUDA version, PyTorch version, etc. were all different. However, this is a realistic situation that may occur when the average researcher updates from their native environment to this template.
As for the realistic estimates, see the [nnUNet](https://github.com/MIC-DKFZ/nnUNet#installation) repository for a discussion by other projects. They find an x2 speedup under realistic training conditions, where speedups are not as impressive due to data transfer times, etc. The reason for better utilization is better optimization of cuBLAS, cuDNN, and other CUDA libraries, as well as the fact that the latest versions are being used. CPU is also probably faster than pip install but I have not checked. Also, using other techniques such as TorchScript are much more effective.

**Comment by seongminp** [comment]
Thank you for the detailed answer! I'll close the issue.

**Comment by skol101** [comment]
Do you think 'computational throughput can be increased dramatically (possibly x10) on the same hardware' can also be achieved during inference?

**Comment by veritas9872** [comment]
@skol101 Please try out the benchmarks. They are designed for inference only. Compared to the naive environments that most practitioners (especially in academia) work in, I would not be at all surprised if a x10 speedup occurs after updating all the software to the latest versions and enabling AMP.

**Comment by veritas9872** [comment]
To be fair, the speedup depends on how naive the initial setup was. The x10 figure is an optimistic figure but based on my personal experience as a graduate student.
